[package]
name = "signer"
version = "0.1.0"
edition = "2021"

[dependencies]
p256 = { version = "0.13", features = ["ecdsa"] }
rand_core = { version = "0.6", features = ["std"] }
sha2 = "0.10"
clap = { version = "4.3", features = ["derive"] }
base64 = "0.21"
thiserror = "1.0"

